### ISSUE TITLE
Special variable DA$ is not recognized

### ISSUE THREAD

**Issue by markjreed** [stefan-b-jakobsson/basload-rom#1]
BASLOAD is treating da$ as a standard variable and translating its name, removing its functionality: 

Basload code:

    NOW$ = DA$ + "T" + TI$ + OFFSET$

Compiled code:

    AE$=AF$+"T"+TI$+AB$

(Originally opened as basload#10)

**Comment by stefan-b-jakobsson** [comment]
This issue has been fixed some time ago. It should be marked as closed.
