### ISSUE TITLE
Wrong error message (coruption issue?) when gosubing missing line label

### ISSUE THREAD

**Issue by jakebullet70** [stefan-b-jakobsson/basload-rom#4]
I am converting a Plus4 program over and ran into this error.  Its all been converted to BASLOAD format now though.
If you go line # 309 it is GOSUB'ing a missing line label. When running the program the error below is happening.

![image](https://github.com/stefan-b-jakobsson/basload-rom/assets/14124210/1038ffd0-dbbc-43e7-a4ef-1c7e4364fe05)

If you REM out that one line the program is converted and runs fine.

[I.zip](https://github.com/user-attachments/files/15521340/I.zip)

**Comment by stefan-b-jakobsson** [comment]
When I run it through BASLOAD (Kernal version pre R47) I get the expected error message:
```
ERROR: LABEL NOT FOUND IN I.B:309
```
Translation of the source file stops when encountering an error. The resulting program isn't complete and you can't expect it to run properly.

**Comment by jakebullet70** [comment]
I have seen the LABEL NOT FOUND message before.  It just stopped as my program has grown in size.

I am using the emulator:
![image](https://github.com/stefan-b-jakobsson/basload-rom/assets/14124210/60f4ee69-c97a-4e09-9bbd-8fbd8672510b)

I would not expect the program to run with any BASLOAD error.  :)

**Comment by stefan-b-jakobsson** [comment]
I downloaded the official R47 Kernal. I still can't see anything unexpected.

https://github.com/stefan-b-jakobsson/basload-rom/assets/70063525/50c5f525-3b36-4a2a-9e3c-aa20b8061d0a

**Comment by jakebullet70** [comment]
Aaaaaaahhhhh, Its me. I am closing this.  I am sorry for taking up your time.  
I have remapped FUNCTION keys that do some work for me and that is my issue.

Again. I am sorry.  :(

**Comment by stefan-b-jakobsson** [comment]
No problem. I'm happy that you use it and report issues :-)
