### ISSUE TITLE
SYM file format needs some work when including files.  

### ISSUE THREAD

**Issue by jakebullet70** [stefan-b-jakobsson/basload-rom#5]
Minor detail...  :) 
Goes to the bottom of the TODO list!  LOL

So in the picture:
FILE: WORKING/ENV-SAVE-LOAD.BL
FILE: WORKING/SOUNDS.BL
FILE: I.B

Should be on there own lines. Something like this

*****************************************************************************
 000245 LINE1710                                            =146;
 000250 LINE1750                                            =149;
 000260 WAIT4KEY                                            =156;
 000265 LINE1810                                            =158;
 000267 LINE1820.SOUND                               =159;

FILE: WORKING/ENV-SAVE-LOAD.BL
 000013 CLOSE.APP                                           =160;
 000018 SAVE.ENV                                            =162;
 000027 RESTORE.ENV                                         =166;

FILE: WORKING/SOUNDS.BL
 000007 SOUND.INIT                                          =168;
 000010 SOUND.CLICK                                         =169;
 000013 SOUND.BOING                                         =170;

*****************************************************************************

![image](https://github.com/stefan-b-jakobsson/basload-rom/assets/14124210/ee668691-3ebb-4df9-a442-04d818601ff3)

**Comment by stefan-b-jakobsson** [comment]
This is a proper bug. It's easily fixed though. Thanks.

**Comment by stefan-b-jakobsson** [comment]
Fixed by commit a3b5160
