### ISSUE TITLE
IF statement - GOSUB issue

### ISSUE THREAD

**Issue by jakebullet70** [stefan-b-jakobsson/basload-rom#6]
Its me again...  :)

REM ------------------------------
CLS
IF 1 = 1 THEN LINE001 
REM --- IF 1 = 1 THEN GOSUB LINE001
END

LINE001:
	LOCATE 10,10
	PRINT "GOSUB ME!"
	RETURN
REM ----------------------------

BASLOADS runs fine but with no error. then when running the program you get:
![image](https://github.com/stefan-b-jakobsson/basload-rom/assets/14124210/46bfc9ac-21b0-4a2d-8eb7-a33b422296ae)

THE line --->    IF 1 = 1 THEN LINE001
needs to be
IF 1 = 1 THEN GOSUB LINE001

it thinks its a goto....
not sure how you really fix that

**Comment by stefan-b-jakobsson** [comment]
Hi,

I believe that this is the behavior of BASIC v 2. THEN followed by a line number is an implied GOTO, not GOSUB.

**Comment by jakebullet70** [comment]
You are correct. 

I will close this - It is just a BASIC V2 idiosyncrasy. 
Been 40 years since I have written any BASIC V2 code and I am only 5 days into the X16 and BASLOAD utility.  
I am having fun!   :)
